name: Re-encode Video V3

on:
  workflow_dispatch:
    inputs:
      input_video_url:
        description: 'URL of the video to download'
        required: true
        default: 'https://drive.google.com/uc?id=1ReH7bi2uQr28dUtYIeiBrLcUL38bpjOb'

jobs:
  reencode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install FFmpeg and Python packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip3 install gdown

      - name: Download Video
        run: |
          VIDEO_URL="${{ github.event.inputs.input_video_url }}"
          
          if [[ "$VIDEO_URL" =~ ^https://drive\.google\.com/ ]]; then
            gdown "$VIDEO_URL" -O input.video
          else
            curl -L -o input.video "$VIDEO_URL"
          fi

      - name: Re-encode video
        run: |
          ffmpeg -i input.video -c:v copy -c:a copy output.mp4

      - name: Set release date
        run: echo "RELEASE_DATE=$(date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV

      - name: Upload re-encoded video
        uses: softprops/action-gh-release@v1
        with:
          files: output.mp4
          name: Re-encoded video
          tag_name: ${{ github.run_id }}
          body: |
            Released on ${{ env.RELEASE_DATE }}
