name: Re-encode Video V4

on:
  workflow_dispatch:
    inputs:
      input_video_url:
        description: 'URL of the video to download'
        required: true
        default: 'https://drive.google.com/uc?id=1ReH7bi2uQr28dUtYIeiBrLcUL38bpjOb'

jobs:
  reencode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FFmpeg and curl
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl

      - name: Download Video
        run: |
          VIDEO_URL="${{ github.event.inputs.input_video_url }}"

          if [[ "$VIDEO_URL" =~ ^https://drive\.google\.com/ ]]; then
            # Extract file ID from the Google Drive URL
            FILE_ID=$(echo "$VIDEO_URL" | grep -oP '(?<=id=)[^&]+')
            # Construct the direct download URL
            DIRECT_DOWNLOAD_URL="https://drive.google.com/uc?export=download&id=$FILE_ID"
            # Use curl to download the video
            curl -L -o input.video "$DIRECT_DOWNLOAD_URL"
          else
            # For non-Google Drive URLs
            curl -L -o input.video "$VIDEO_URL"
          fi

      - name: Re-encode video
        run: |
          ffmpeg -i input.video -c:v copy -c:a copy output.mp4

      - name: Set release date
        run: echo "RELEASE_DATE=$(date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV

      - name: Upload re-encoded video
        uses: softprops/action-gh-release@v2
        with:
          files: output.mp4
          name: Re-encoded video
          tag_name: ${{ github.run_id }}
          body: |
            Released on ${{ env.RELEASE_DATE }}
