name: Re-encode Video

on:
  push:
    branches:
      - main

jobs:
  reencode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Download Video
        run: |
          VIDEO_URL="https://drive.google.com/file/d/19P7NLoo0Z-031bgLXHFPzq2k2Fe0LAzq/view?usp=drivesdk"  # Replace with your video link
          curl -L -o input.mp4 $VIDEO_URL

      - name: Re-encode video
        run: ffmpeg -i input.mp4 -vcodec libx264 -crf 23 output.mp4

      - name: Upload re-encoded video
        uses: actions/upload-artifact@v2
        with:
          name: reencoded-video
          path: output.mp4
