name: Passthrough GoFile

on:
  workflow_dispatch:
    inputs:
      input_video_url:
        description: 'URL of the video to download'
        required: true
        default: 'https://drive.google.com/file/d/1-0qWa13-22m12XPJhMIewzYnuTS8phdm/view?usp=drivesdk'

jobs:
  reencode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FFmpeg, curl, and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl jq python3-pip
          pip3 install gdown

      - name: Download Video
        run: |
          VIDEO_URL="${{ github.event.inputs.input_video_url }}"

          # Extract the Google Drive file ID if it's a Google Drive link
          if [[ "$VIDEO_URL" =~ ^https://drive\.google\.com/file/d/([^/]+)/ ]]; then
              FILE_ID="${BASH_REMATCH[1]}"
              DIRECT_DOWNLOAD_URL="https://drive.google.com/uc?export=download&id=$FILE_ID"
              
              # Attempt to download using gdown, fallback to curl
              gdown "$DIRECT_DOWNLOAD_URL" -O input.video || curl -L -o input.video "$DIRECT_DOWNLOAD_URL"
          else
              # For non-Google Drive links, directly use curl
              curl -L -o input.video "$VIDEO_URL"
          fi

      - name: Re-encode video
        run: |
          ffmpeg -i input.video -movflags +faststart -c:v copy -c:a copy output.mp4

      - name: Upload Video to GoFile
        run: |
          #!/bin/bash

          FILE="output.mp4"

          if [[ ! -f "$FILE" ]]; then
              echo -e 'ERROR: File not found!' && exit 1
          fi

          SERVER=$(curl -s https://api.gofile.io/servers | jq -r '.data.servers[0].name')
          LINK=$(curl -# -F "file=@$FILE" "https://${SERVER}.gofile.io/uploadFile" | jq -r '.data|.downloadPage') 2>&1

          echo "$LINK"
